adopted-ember-addons/ember-paper

tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/navigation.hbs

When I tried this out the main content was ending up behind the sidebar navigation, I looked at your dummy app and it was using this classname so i added it to the documentation

Adding missing classname that makes the navigation work

---

README.md

This will `npm install --save-dev` the addon, and then also run the generator with the same name. Crazy!
This was [introduced in ember-cli 0.1.5](https://github.com/ember-cli/ember-cli/blob/master/CHANGELOG.md#015)

Use ember-cli install command for addons

---

package.json
postinstall.sh

One of the main issues causing safari to not function properly was the lack of using the `-webkit` vendor prefix for flexbox layouts. Adding autoprefixer and setting it to use the last 2 browsers should ensure that `ember-paper` works properly in Safari as well as IE 10.
See miguelcobain/ember-paper#31 for additional details / discussion.

Applying autoprefixer. Fixes miguelcobain/ember-paper#31.

---

addon/components/paper-icon.js
addon/styles/scss/paper-icon.scss
tests/dummy/app/templates/icons.hbs

using classes to create multiple sizes of `paper-icon` and css animation for spinners.
the added classes are:
`.md-lg`  for large icon (1.5em)
`.md-2x` 2x default icon
`.md-3x` 3x default icon
`.md-4x` 4x default icon
`.md-5x` 5x default icon
`.md-spin` clockwise spinner
`.md-spin-reverse` anti-clockwise spinner

Add feature for Icon sizes and spinners using classes

---

app/templates/components/paper-text.hbs

paper-text does not currently pass the `required` attribute to the underlying `input`. This PR resolves that by simply passing that attribute to the `input`.

paper-text should pass the 'required' attribute

---

blueprints/ember-paper/files/app/styles/app.scss

`ember g ember-paper` will attempt to install `app.scss`.  If it's already there, the developer will at least see that they should add `@import 'ember-paper';`

Add app.scss to Blueprint

---

addon/components/paper-backdrop.js

For some reason the default `click` event wasn't working on iOS.  I swapped it
out with a Hammer event and it seems to work much better now.
Closes #57

Fix dismissing sidenav on iOS

---

addon/components/paper-radio.js
tests/dummy/app/routes/application.js
tests/dummy/app/templates/radio.hbs
tests/unit/components/paper-radio-test.js

Allows you to call an action after a user interaction causes your `selected` value to update. Preferred over adding observers on the `selected` value.
Same as: https://github.com/yapplabs/ember-radio-button

Expose changed action on paper-radio

---

README.md
bower.json
index.js
package.json
tests/dummy/app/app.js
tests/dummy/app/templates/index.hbs

I started working on an update to ember-cli 0.2.5. Right now this is a pretty minimal approach: just compare the diff from `ember update` and adjust appropriately.
There are probably still some things that should be done, either with this PR or soon after. In particualar I can think of the following:
- Move to `ember-cli-sass` as this is the recommenced tool to use for Sass according to the docs. I have an initial attempt in this branch https://github.com/rxfork/ember-paper/tree/ember-cli-sass ~~but when I test with `ember serve`, the css files are 404. I tried following the [Addon Usage section](https://github.com/aexmachina/ember-cli-sass#addon-usage) in the docs but it didn't fix it for me. Maybe it is expecting a different folder structure? Not sure here.~~ Works now and added to PR. …

Ember cli 0.2.5

---

.gitignore
addon/components/paper-slider.js
addon/mixins/events-mixin.js
app/components/paper-slider.js
app/services/constants.js
app/styles/color-palette.scss
app/styles/ember-paper.scss
app/styles/paper-slider.scss
app/styles/variables.scss
app/templates/components/paper-slider.hbs
tests/dummy/app/controllers/slider.js
tests/dummy/app/router.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/slider.hbs
tests/unit/components/paper-slider-test.js
tests/unit/services/constants-test.js

I combined the paper-slider component my [ember-material-design](https://github.com/mike1o1/ember-material-design) project and added a demo page. 
There are some .scss differences, as I have a `color($color, $type)` method, which tries to mirror the theming support from the angular project. If you'd rather those be simple `map-get` calls, I can refactor.

Add paper-slider component

---

blueprints/ember-paper/index.js

Hi!
I tried to user `ember-paper` in my project and got this error while installation process:
```
version: 0.2.7
Installed packages for tooling via npm.
installing
create app/styles/app.scss
Cannot call method 'match' of undefined
TypeError: Cannot call method 'match' of undefined
at Object.decompose (/private/var/www/try-paper/node_modules/ember-cli/node_modules/bower/node_modules/bower-endpoint-parser/index.js:4:28)
at /private/var/www/try-paper/node_modules/ember-cli/node_modules/bower/lib/commands/install.js:22:31
at Array.map (native)
at install (/private/var/www/try-paper/node_modules/ember-cli/node_modules/bower/lib/commands/install.js:21:30)
at /private/var/www/try-paper/node_modules/ember-cli/node_modules/bower/lib/commands/index.js:21:32
at Promise.apply …
```

Fix `ember install ember-paper` errors

---

tests/dummy/app/templates/button.hbs

Paper button could be used together with paper-icon as shown in the example in [this](http://miguelcobain.github.io/ember-paper/#/button) page. However, the code template is missing example code to use paper-button with paper-icon. This pull request added the missing code.
Thank you and great work on the ember paper project!

Add missing code template for button with icon

---

addon/components/paper-progress-linear.js
app/templates/components/paper-progress-linear.hbs

This PR fixes deprecation notice for progress-linear, tested with (1.13.3):
```
DEPRECATION: A property of <dummy@view:-outlet::ember279> was modified inside the didInsertElement hook. You should never change properties on components, services or models during didInsertElement because it causes significant performance degradation.
```

Fix deprecation: paper-progress-linear

---

CHANGELOG.md
addon/components/paper-progress-circular.js
app/components/paper-progress-circular.js
app/styles/ember-paper.scss
app/styles/paper-progress-circular.scss
app/templates/components/paper-progress-circular.hbs
tests/dummy/app/controllers/progress-circular.js
tests/dummy/app/router.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/progress-circular.hbs
tests/unit/components/paper-progress-circular-test.js

- Converted from ember-material-design
- Added tests
- Uses the new color mixin just as paper-progress-linear.

Feature: paper-progress-circular component

---

addon/components/paper-autocomplete-list.js
addon/components/paper-autocomplete.js
app/templates/components/paper-autocomplete.hbs
tests/unit/components/paper-autocomplete-list-test.js

Fixes:
- autocomplete initial rendering problem (by removing that ugly observer I created and not use isVisible!! So we don't trigger the computed property `suggestions` on-load.)
- fixes select item by ENTER key. 
- Also fixes focus problem if input was empty before the autocomplete did not open: It only opened if some text was there -> focus out  -> focus in. Now it works if empty text -> focus in [open if min-length was correct.].

Fixes autocomplete initial rendering problem, select by ENTER + focus problem.

---

CHANGELOG.md
addon/components/paper-icon.js
app/styles/paper-icon.scss
tests/dummy/app/templates/icons.hbs

Icon sizes were disabled because the css was commented for some reason. I have fixed those and also added a new size 'md-sm' for smaller icon sizes.

fixed icon size parameters and added 'md-sm'

---

addon/components/paper-input.js
app/templates/components/paper-input.hbs
tests/dummy/app/styles/app.scss
tests/dummy/app/templates/input.hbs

Also add support for placeholder text, and add option to hide all error messages. If no label value, don't render the label element, so that user can opt out of floating labels by using placeholders instead.

Add support for inline paper-icon in paper-input component.

---

blueprints/ember-paper/index.js

Fixes a missing dependency added by https://github.com/miguelcobain/ember-paper/pull/138.

Add matchMedia to bower.json

---

tests/dummy/app/templates/autocomplete.hbs

Block parameters were not in the right order in one example

Fix autocomplete doc

---

addon/components/paper-button.js

Allow `type` attribute to be passed to the `{{paper-button}}` component

Allow 'type' attribute on {{paper-button}} component

---

addon/components/paper-grid-list.js

fixes #196 
Fix assertion thrown when invalidating destroyed `paper-grid-list` component.

check if grid list is destroyed before invalidating it fixes #196

---

CHANGELOG.md
index.js
tests/dummy/app/templates/application.hbs

Instead of needing to include the Wormhole outlet in your application manually, the addon will now add the `div` automatically.
Note: I'm not sure if this will be backward compatible with having it also defined in the template, for people that already are using it the previous way.
Closes #214

Inject wormhole outlet through addon hook

---

app/styles/paper-select.scss

Same fix as #209 for a couple of different colors.  I searched the project and these appear to be the last two references to color definitions that don't use the `color` utility function.

Fixed a few stray color references that didnt use color utility

---

CHANGELOG.md
addon/components/paper-sidenav.js
tests/dummy/app/styles/app.scss
tests/dummy/app/templates/sidenav.hbs

In response to #204 (fixes #204)
* `closeOnClick` defaults to `true`, making this option backwards compatible.
* Updated changelog
* Updated sidenav docs with attribute and example code fix (formatting was horrible)
* Fixed doc site not scrolling

Add `closeOnClick` to paper-sidenav

---

addon/components/paper-icon.js
tests/integration/components/paper-icon-test.js

* Adds tests for `paper-icon` (previously untested)
* Adds positionalParam support so you can now do `{{paper-icon "check"}}` in addition to `{{paper-icon icon="check"}}`

Improvements to `paper-icon`

---

bower.json
package.json
tests/dummy/app/routes/application.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/sidenav.hbs

- Upgraded ember demo site to 2.3.0
- Use [transition-to](https://github.com/peec/ember-route-action) addon to route from components. This is not included as a dependency but rather dev-dependency.

Upgrade to ember 2.3.0 and use "transition-to" helper

---

addon/components/paper-menu.js

This allows the current paper-menu to be used for drop-down menus (of a sort).

Uncomment paper-menu positioning for top/bottom and left/right

---

addon/components/paper-icon.js
tests/integration/components/paper-icon-test.js

Closes #276.
A back-port of #290.

Add aria-label support to `paper-icon`

---

.travis.yml

This is to work around an ember-cli issue where the addon folder is not being linted. We should probably remove this line once it is fixed upstream.
If this PR is implemented correctly, it should *fail* the automated Travis testing.

Run JSCS on addon folder in Travis

---

app/styles/color-palette.scss

This is zkwentz's PR to allow style color variables to be overridden by declaring them with !default. This PR applies to the WIP/1.0.0 branch, rather than master. I believe that active new features are being added in this branch.
Credit to zkwentz, not me. :+1:

Fix #193 by zkwentz. Allow scss override via !default.

---

addon/components/paper-autocomplete-list.js
addon/components/paper-input.js
addon/components/paper-menu.js
addon/components/paper-select-core.js

#299 reports a regression where `let [x] = someJqueryObject;` raises an exception because Babel expects the right-side expression to be an actual Array or iterable object, which jQuery objects aren't

Fix #299: Regression cause by array spread with jQuery objects.

---

app/styles/ember-paper.scss

This PR adds back the CSS which was lost in the conversion to importing from angular-material. I have searched angular-material-source for references to the CSS class md-spin and there are none.

Fixes #296: CSS for class md-spin and md-spin-reverse is missing. Icons don't spin.

---

CHANGELOG.md
addon/components/paper-menu-content-pane.js
app/templates/components/paper-menu-content.hbs
app/templates/components/paper-menu.hbs

Angular defines a md-dense style, but because it needs to be applied in the paper-menu-content-pane, which is in the paper-menu-content, which is in turn in the paper-menu, there is no easy way for md-dense to be specified. This PR adds a "dense=true" option to paper-menu, which "bubbles down" (sinks??) down to the paper-menu-content-pane, where it adds the required class.

Allow paper-menu's to be displayed with md-dense.

---

CHANGELOG.md
addon/components/paper-card-title-media.js
addon/components/paper-card-title-text.js
addon/components/paper-card-title.js
app/components/paper-card-title-media.js
app/components/paper-card-title-text.js
app/components/paper-card-title.js
app/styles/paper-card.scss
tests/dummy/app/styles/demo.scss
tests/dummy/app/templates/card.hbs

Adds a few components to expand potential layouts of `paper-card` by providing analogs of the card title components found in Angular Material (https://material.angularjs.org/latest/demo/card):
- paper-card-title: Can be used in place of, or in conjunction with, paper-card-content to display card title text and images.
- paper-card-title-text: Displays some title text.
- paper-card-title-media: Displays a title image in the upper right corner of the card.
Example:
```handlebars
{{#paper-card class="card-lg-media-demo"}}
{{#paper-card-title}}
{{#paper-card-title-text}}
<h2>Paracosm</h2>
<p>The titles of Washed Out's breakthrough song and the first single from Paracosm share the...</p>
{{/paper-card-title-text}}
{{#paper-card-title-media}}
{{/paper-card-title-media}}
{{/paper-card-title}} …
```

Add paper-card title components

---

addon/components/paper-icon.js
tests/integration/components/paper-icon-test.js

Closes #276.
Do we want to back-port this to `<1.0.0`?
I've also set it up to be a clean merge from current `wip/v1.0.0`. If #289 is merged, this will need to be adjusted (to use `icon` rather than `iconClass`).

[1.0.0] Add aria-label support to `paper-icon`

---

CHANGELOG.md
index.js

The `paper-wormhole` div is currently insterted into the `<head>` of the index.html page,
which causes DOM parsing problems for browsers. The `div` element cannot appear in the
`<head>`, and causes Chrome to move the `<body>` tag up to enclose the first `<div>`, breaking
all subsequent `<head>` tags (favicons meta, etc.)
This change places the tag as the first element in the `<body>` tag, which should
be equivalent for Paper.

Move `paper-wormhole` div out of head tag.

---

addon/components/paper-dialog-inner.js
addon/components/paper-dialog.js
addon/mixins/translate3d-mixin.js
app/templates/components/paper-dialog.hbs
tests/dummy/app/controllers/dialog.js
tests/dummy/app/templates/dialog.hbs
tests/integration/components/paper-dialog-test.js

`parent`, `origin`, `openFrom`, `closeTo` are all optional and all take a jQuery selector or jQuery object.
I found the original API inconsistent and inconvenient in actual use. This PR normalized the API and cleans up some old code remnants. 
Note that `parent` is *not* an id, but a jQuery selector or object. An id is created, if needed, for `{{ember-wormhole}}`.

Dialog API buff-up.

---

CHANGELOG.md
app/templates/components/paper-autocomplete.hbs
tests/dummy/app/templates/autocomplete.hbs

Inverse component templates can not recieve parameters. This means
there is no access to `searchText` in the inverse block.
- Try to render notFoundComponent then inverse block then default notFoundMsg
- Update documentation app to reflect that searchText is not available in inverse bloc.
See: https://github.com/emberjs/ember.js/pull/11084

Update inverse template for autocomplete as it doesnt accept parameters

---

addon/components/paper-menu-abstract.js
addon/components/paper-menu-content-pane.js
addon/components/paper-menu-item.js

This is just a minor update to this one file to allow my development to proceed. It adds two actions: `onMenuOpen` and `onMenuClose`. I would have named these `onOpen` and `onClose` but for the existing attribute `onMenu`, which accepts a promise that yields menu items.
@miguelcobain: My hope is to merge this into `wip/v1.0.0` as a minor update, rather than taking on all of the menu-related components right now.
To-do:
Consider renaming `onMenu` to `getItems` so that the actions can be `onOpen` and `onClose`.

paper-menu: update paper-menu-abstract to ES6 and add onOpenMenu/onCloseMenu

---

package.json

ember-paper runs autoprefixer in a postprocessTree hook, it therefore must run before ember-cli-sri or sri errors will ensue

Fix SRI issue #224

---

index.js

3 minor changes:
- add ember-route-action to dependencies instead of devDependencies
- point to the projects nodeModulesPath - this allows consumers to see angular-material-source in their node_modules directory(and keeps the demo working as well)
- changed the version back to 0.2.12 as it was overwritten in 8b7dd871496e312afad5ef0d9e928a36307ebdfd

fix dep errors + version number

---

index.js

While adding Ember Fastboot support to an application, I was receiving:
```javascript
$ ember fastboot --serve-assets
Built project successfully. Stored in "fastboot-dist".
Installing FastBoot npm dependencies
document is not defined
ReferenceError: document is not defined
```
This was because HammerJS and MatchMedia use the `document`, but NodeJS, which Fastboot uses, doesn't use the `document`, which leads the `ReferenceError`. Therefore, if Ember Fastboot is requiring `ember-paper`, lets skip HammerJS and MatchMedia.

don't import hammerjs and match media if being called from node

---

addon/components/paper-switch.js
tests/integration/components/paper-switch-test.js

Fixed a couple of issues I've noticed:
1. When a pressed switch looses focus, and then re-gains it - the thumb must glow.
1.a. Further changes to the pressed/unpressed state must keep the thumb glowing.
1.b. When tapping the thumb ripple should be generate over the glow.
2. Clicking on the actual switch should not generate ripple effect on the thumb.
3. Space/Enter key on focused switch should behave like 1.a.
4. Fixed the drag --> was using the wrong elemen's innerWidth()
Compare this <-> ember-paper/master <-> angular md

Switch component must behave exactly like md angular example

---

tests/dummy/app/templates/sidenav.hbs

The `ember-route-action` addon isn't easily discoverable at the moment, so explicitly including a link to the repository is arguably more valuable than printing the given `ember install` command.

link directly to `ember-route-action` helper

---

addon/components/paper-button.js
tests/dummy/app/templates/button.hbs
tests/integration/components/paper-button-test.js

Added fab and mini class name bindings, with tests and examples in dummy app. I appreciate any feedback I am still new to this.

md-button class bindings

---

addon/components/paper-toolbar.js
tests/dummy/app/templates/toolbar.hbs
tests/integration/components/paper-toolbar-test.js

New *tall* class name binding for paper-toolbar, with test and example in documentation. Let me know what I can do to improve the test, I am still new to Ember and testing with it.

Toolbar class bindings

---

index.js

- Angular-material-source does not have a main node module, its only
built to ./dist and published via bower. The first attempt to make
this work with npm 3.x broke (some users) npm 2.x env's.
- This aims to allow building a project that includes this addon for
npme 2.x and 3.x for all versions of node.
fixes #349

Fix npm 2.x build failures for angular-material-source dependency

---

CHANGELOG.md
addon/components/paper-button.js
tests/dummy/app/templates/button.hbs
tests/dummy/app/templates/dialog.hbs
tests/dummy/app/templates/index.hbs
tests/dummy/app/templates/toolbar.hbs
tests/integration/components/paper-button-test.js

Also Improve dummy app page with API documentation and button. Use a-link style button to link from 1.0 dummy app to v0.2.

paper-button: Support `<a>` tags with href and optional target attributes.

---

addon/components/paper-menu-container-abstract.js

Problem was that the md-active class (which mandated that the display be block) was being removed before the transition started, causing the 'display:none' from paper-select-container to interrupt the transition. The reason it worked in dummy app was that dummy app forces all ember-views to have display flex.
Looked at AM code and it appears the correct solution was to remove md-active after the transition ended.

Fixed paper-select issue

---

addon/components/paper-menu-item.js

problem with #378 was that mouseEnter events on menu items should trigger a focus if there is a non-disabled md-button inside the menu item. Corresponding AM code can be seen here:
https://github.com/angular/material/blob/master/src/components/menu/js/menuController.js
in ```this.handleMenuItemHover()```.

fix for issue #378

---

addon/components/paper-progress-linear.js
app/templates/components/paper-progress-linear.hbs
tests/dummy/app/controllers/demo/progress-linear.js
tests/dummy/app/templates/demo/progress-linear.hbs

Before this fix, the determinate progress bar was getting 'stuck'
because the bar style wasn't bound to the mode. So when the mode
changed, the bar style wasn't updated.

Fixes query linear progress to demo switch from query to determinate.

---

tests/dummy/app/controllers/application.js

This method used in the dummy app is not natively supported by IE11 and breaks Ember.

replace startWith with substr

---

addon/components/paper-divider.js
app/services/constants.js
tests/dummy/app/controllers/demo/divider.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/demo/divider.hbs
tests/integration/components/paper-divider-test.js

Nothing fancy here...
Added documentation and integration test for divider component. 
Removed insetAttr computed property, in favor of explicitly defined inset property which defaults to null.

Divider cleanup, docs and test

---

addon/components/paper-select-core.js
app/templates/components/paper-select.hbs

paper-select was never calling the onChange action even though it is required.

changed paper-select to call onChange instead of setting value directly

---

addon/components/paper-input.js
app/templates/components/paper-input.hbs
tests/integration/components/paper-input-test.js

There was an issue with onInvalid being sent multiple times when isInvalid goes from TRUE <=> NULL.
Because these essentially both are invalid states, it's unnecessary to send multiple invalid actions.

Prevent redundant on invalid

---

tests/dummy/snippets/content-security-policy.js

The readme is updated, but it looks like the docs' snippet was missed.

Whitelists google font stylesheets in CSP snippet.

---

tests/dummy/app/templates/demo/input.hbs

minor typo in the documentation of the example app, but might cause some confusion for new users doing a naive copy and paste, which would still build but would display the default required error msg and not the custom errorMessage specified.

typo in Input example for errorMessages required

---

addon/components/paper-menu-content-inner.js
addon/components/paper-menu-content.js
addon/components/paper-menu-item.js
app/templates/components/paper-menu-content-inner.hbs
app/templates/components/paper-menu-content.hbs
tests/dummy/app/templates/demo/menu.hbs
tests/integration/components/paper-menu-test.js

I also made the menu-items contextual components in order to use the ParentMixin and ChildMixin. Obviously neither is really necessary but you already had ParentMixin so I assumed that's the direction you wanted to go.

Added keyboard support for paper-menu

---

addon/components/paper-input.js
tests/dummy/app/templates/demo/input.hbs

Issue arose when using the ember-i18n add-on with paper, specifically for providing translation for paper input validator errorMessages
```
{{paper-input
value=identification
label=(t "label.email")
class="md-block"
onChange=(action (mut identification))
required=true
errorMessages=(hash required=(t "paper.required”)) 
}} 
```  
this returned a console error: `vendor.js:151199Exception with validation:  Object TypeError: str.replace is not a function”  `
temporary work around would involve doing ; 
errorMessages=(hash required=(get (t "paper.required") "string"))
(@miguelcobain further suggest looking into Ember.String.loc and why it doesn't work with safe strings :/ )

allow SafeString in paper-inputs validation errorMessages

---

CHANGELOG.md
app/templates/components/paper-radio-group.hbs
tests/dummy/app/templates/demo/radio.hbs
tests/integration/components/paper-radio-group-test.js

Changed all of the group.paper-radio contextual components over to be just group.radio (including tests, dummy app, and changelog)

Changed the usage of paper-radio inside of paper-radio-group

---

tests/dummy/app/templates/index.hbs

Since `ember install ember-paper` now installs 1.0 by default we need to update the copy to reflect this. It looks like the changes have already been made to the snippets but it hasn't been deployed to github pages yet.

Update latest version copy as 1.0-alpha is default

---

addon/components/paper-sidenav-inner.js
app/services/sniffer.js
package.json

using the `FastBoot` global to determine if it is in FastBoot mode

fixed fastboot service check

---

addon/components/paper-form.js

Added ability for users who don't want to always disable the submit button, to display all the errors in the form upon the user interacting with the submit button prior to all fields being valid.

Added Form Feature - Show Errors Upon Submit if Not Disabled

---

index.js

The "last 2 versions" rule for the autoprefixer was not sufficient to add "display: -webkit-flex" support for Safari v8.0.6 and Safari in iOS Simulator v8.3. All Flexbox based features were broken as a result.

Added autoprefixer support for Safari >= 6 to use -webkit-flex

---

addon/mixins/ripple-mixin.js
app/styles/backports/ripple.scss
app/styles/ember-paper.scss

Once we move to angular-material >= 1.1.0 we can remove those backported styles

Fix ripple artifact in Chrome 51

---

addon/components/paper-menu-content-inner.js

It's possible to generate an error if there is no valid focusTarget in the menu, this should resolve that issue by checking to see if focusTarget is defined before trying `focusTarget.focus()`

add guard in case focusTarget undefined

---

addon/components/paper-menu-content-inner.js
addon/components/paper-menu-item.js
app/templates/components/paper-menu-content-inner.hbs

The tests that are failing are autocomplete related and should be resolved once you merge my other PR.
This PR closes the dropdown after an item has been clicked, this is the behavior of AM menus.

Close menu on click

---

addon/components/paper-dialog-content.js

without this change the browser throws an error when jquery tries to do a .indexOf on an anonymous function instead of a string

referencing the correct API

---

index.js

Without this, attempting to use paper-autocomplete in an app (or other addon) results in:
ember-wormhole failed to render into '#ember-basic-dropdown-wormhole' because the element is not in the DOM
See https://github.com/cibernox/ember-power-select/issues/145#issuecomment-170012836 for more detail

Call power-select's contentFor hook for body-footer

---

addon/components/paper-input.js
tests/dummy/app/templates/demo/input.hbs

paper-input used the correct algorithm for determining height from 1.0.6, however they've changed it radically and I think that the newer version was always the intended behaviour. passThru.rows is meant to be the *minimum* number of rows, not the maximum. I've added another property maxRows to allow them to specify that behavior.

changed growTextArea algorithm to follow more recent spec

---

package.json

This fixes a memory leak, as well as fixing and improving a few other things.  Also bump minimum version of ember-basic-dropdown in core requirements to match that in e-p-s beta.19, to get some of the same fixes when using e-b-d directly.

Upgrade paper-menu branch to ember-power-select 1.0.0-beta.19

---

addon/components/paper-menu-content.js

Had a problem where the component was destroyed before the animations were finished and the menu stayed behind. This should remove the clone regardless of whether the component has been destroyed to prevent visual glitches.

clone still needs to be removed if the component has been destroyed

---

addon/components/paper-input.js

* ensures hooks higher up in mixinx will fire properly
this was causing an error when we were using the `paper-form` input and dynamically adding/removing its child components in the form based on the current form data.

Add super calls inside paper-input lifecycle hooks.

---

addon/components/paper-select-content.js

under Glimmer 2 there is a new DOM mutation that wasn't there before. It's the addition of a `comment` node that happens under a number of circumstances, such as hovering over one of the options or the window losing focus. The reposition for paper-select includes changing the scrollTop value to center around selected values when the menu initially renders but that should only happen on initial render.
I'm asking the ember team about the nature of this node but regardless it likely is never desirable to trigger a reposition after adding it so I filtered it out of the DOM mutations that should rightfully trigger reposition.

Fix Glimmer 2 scroll for paper-select

---

package.json

v0.1.2 was the most recent non-breaking version published to npm.
This fixes https://github.com/miguelcobain/ember-paper/issues/512

pinning the version of ember-css-transistions as v0.1.5 was a breaking change

---

addon/components/paper-autocomplete.js
package.json

Use ember-power-select 1.0.0-beta.23's new `defaultHighlighted` option to override its default highlighting (on open and filter/search) to match AM's behaviour - not highlighting anything.  Keyboard or mouse can be used to select an option from the dropdown.

paper-autocomplete: don't highlight options by default

---

index.js

This fixes issues with people seeing `regeneratorRuntime` is not defined when ember-concurrency / ember-maybe-import-regenerator are deeply nested dependent addons.
[This new ember app](https://github.com/v3ss0n/ember-paper-menu-error-concurrency) demonstrates the bug and is fixed with this change to ember-paper.
Prior art: https://github.com/ember-cli/ember-cli/issues/3718#issuecomment-88094450

fix `included` _super class

---

index.js

I don't have a good way to test compatibility with all node and npm versions but this change should only be additive and does work for me with npm v3 and with yarn.

Update Angular SCSS import to work with yarn's flat node_modules

---

tests/dummy/app/templates/demo/sidenav.hbs

The component `paper-sidenav-toggle` now has a `tagName` of `''` so adding a class to it as shown in the demo doesn't work and `Toggle` is visible on all screen sizes.

Moved "hide-gt-sm" class in sidenav demo.

---

addon/components/paper-select-menu-inner.js

Should not try to call focusTarget.focus if there is no focusTarget (which is perfectly possible).

paper-select focus fix

---

addon/components/paper-autocomplete.js
app/templates/components/paper-autocomplete-trigger.hbs
app/templates/components/paper-autocomplete.hbs
app/templates/components/paper-form.hbs

Added contextual components to paper-form for select and autocomplete. Interesting issue with autocomplete is that there are two properties that we may want to watch for validation over but currently validation-mixin only supports a single validation property. For now I set it to do validation on searchText but that can be changed by the user by passing in validationProperty='selected'.
Validation messages for autocomplete will only show up for the floating label version for obvious reasons.

validation for autocomplete and change to form

---

addon/components/paper-autocomplete.js

ember-cli ships with these `"predefs"` in `.jshintrc`
```
"predef": [
"document",
"window",
"-Promise",
"moment"
]
```
`self.document` was causing JSHint errors when running tests.  Changed `self.document` to `document` to work with default ember-cli defs.

`self.document` to `document` to resolve JSHint issue

---

addon/components/paper-input.js

This fixes an issue with auto-grow when rendering a textarea that already had a `value` passed in (without user input).

Set the value before growing the textarea on render

---

addon/components/paper-autocomplete-trigger-container.js

Currently, touch devices are unable to focus on the input in paper-autocomplete because ember-basic-dropdown does a preventDefault on the touch event that prevents the focus event from being called on the input. This corrects that issue.

allow touch devices to interact with autocomplete

---

CHANGELOG.md
addon/components/paper-input.js

I got the following exception on paper-input when typing with the Android keyboard:
[paper-input error](https://drive.google.com/file/d/0B_CrumEitcQDREFQaVRLc1UtczA/view?usp=sharing)
Cannot read property 'val' of undefined.
Steps to reproduce:
requirements:
Android smartphone with google chrome
1. Open Chrome dev tools and setup it for [remote debugging](https://developers.google.com/web/tools/chrome-devtools/remote-debugging/)
2. On the phone open this page [dialog example](http://miguelcobain.github.io/ember-paper/release-1/#/components/dialog)
3. In the prompt dialog example type some text with the phone keyboard (has to be with the phone keyboard)
4. Click on confirm action on the dialogue 
Expected:  Dialog closes
Actual: Dialog remains opened  with the error linked above
The fix in …

[paper-input] preventing exception when typing with mobile keyboard

---

tests/dummy/app/templates/layout/layout-containers.hbs

the max-width is set to 100% so max-height is the the height of the items in the container, not the width

[DEMO] width should be height

---

app/templates/components/paper-virtual-repeat.hbs

sometimes it is desirable to have the list items render outside of the virtual repeats offsetter. In particular, using VR in conjunction with tables (such as paper-data-table) requires the table to be rendered as a sibling of the offsetter to work correctly.
I'd also like to remove the virtual-each class from the paper-virtual-repeat, I'm not sure how to do that though since it's being added by the parent class and doesn't appear to be overridden by the paper-virtual-repeat implementation.

VR: ignore offsetter parameter

---

addon/components/paper-autocomplete.js

To reproduce:
1. In e-p current demo (v1.0.0-alpha.8), click on any autocomplete, then hit 'tab' key w/o selecting/highlighting any items
2. The autocomplete drop-down stays open
Fix:
- When tab is invoked, just delegate to e-p-s component, which closes the drop-down by default.

Close autocomplete drop-down on tabKey

---

app/templates/components/paper-form.hbs
tests/integration/components/paper-form-test.js

Specify the type of paper-form button as submit so that the form can be submitted using enter key
See #460

automatically set the type of submit-button to submit

---

app/templates/components/paper-autocomplete-trigger.hbs
app/templates/components/paper-autocomplete.hbs
tests/dummy/app/templates/demo/autocomplete.hbs

1. Support required attribute on autocomplete similar to paper-input (shown
with a start (*))
2. Allow passThru hash to passed in.

Make autocomplete similar to paper-input (required star & passThru hash)

---

addon/components/paper-autocomplete-trigger.js
app/styles/backports/paper-autocomplete.scss
app/styles/ember-paper.scss
tests/dummy/app/templates/demo/autocomplete.hbs

Fix autocomplete clear button's position when floating label is used

---

addon/components/paper-autocomplete-highlight.js
tests/integration/components/paper-autocomplete-test.js

When the label in a `paper-autocomplete-highlight` points to a property that is not Text the call to `replace` on  the property will fail.
An example use case is having an autocomplete of some sort of number. eg. Product codes, employee numbers...

Autocomplete highlight non Text

---

CHANGELOG.md
app/templates/components/paper-dialog.hbs
tests/dummy/app/templates/demo/dialog.hbs
tests/integration/components/paper-dialog-test.js

Add the capability for the user to specify CSS classes to the paper dialog container if necessary.

can add CSS classes to paper dialog container

---

tests/dummy/app/styles/app.scss

Because the test app share its css with the dummy app. It had the 'overflow:hidden' css property which prevent the user from scrolling.
This property seems unnecessary as it does not appear* to affect the dummy app in anyway.
* tested on chrome only

remove overflow:hidden directive on body tag that breaks test app

---

.gitignore
.travis.yml
bower.json
config/ember-try.js
package.json
tests/helpers/start-app.js
tests/index.html

Also includes `ember init`, which changed the ember try config slightly. Let me know what you think.
I tested the dummy app using 2.9 and 2.10 and found no differences. 2.10 felt a little faster on pages with a lot of components (like the input demo), but that's subjective.
|gzipped|size 2.9 | size 2.10 | reduction |
|---|---|---|---|
no |988.15 KB |465.31 KB | 53%
yes |103.81 |64.74 KB | 38%
Probably slightly skewed because the dummy app almost entirely consists of templates.

Update Ember, Ember CLI and Ember Data to 2.10

---

addon/components/paper-chips.js
app/templates/components/paper-autocomplete-trigger.hbs
app/templates/components/paper-chips.hbs
app/templates/components/paper-select.hbs

Fixes a bug where clicking on paper-select component would cause paper-autocomplete w/o a label to also display its own dropdown options.

Paper-autocomplete options must only be shown when interacted with

---

addon/components/paper-menu-content.js

When using paper-select with async search and no options specified, the menu will reposition itself when the loading spinner shows. This makes it look janky to do async searches so we should ignore the spinner change.

search fix

---

tests/dummy/app/templates/demo/chips.hbs

This fixes display in IE11 (see #616).  Note that there are other compatibility issues with IE11, but this at least allows you to see the chips demos in order to work on them.

Demo - Chips: Remove class="flex" from paper-card-content elements

---

index.js

With this little fix the ember-addon will be able to retrieve the parent application while being used from another addon. 
This also provides compatibility for ember version lower than 2.5 which don't provide the findHost helper

Modification to the index.js include directory

---

addon/components/paper-backdrop.js

`translateStyle` was leftover and undefined.
Fixes #638

remove translateStyle from backdrop

---

CHANGELOG.md
index.js

Added check on ENV.useFontsFromAssets to prevent the insertion of links to fonts.googleapi.com in the contentFor hook

Prevent insertion of font links in head element

---

addon/components/paper-form.js
addon/templates/components/paper-form.hbs
tests/dummy/app/templates/forms.hbs
tests/integration/components/paper-form-test.js

My second attempt at solving https://github.com/miguelcobain/ember-paper/issues/460, this time by making `paper-form` an html form.
Some things to note:
- Pressing the enter key to select an item in a `paper-autocomplete` (as well as a `paper-select` I assume) will submit the form - probably not ideal behavior. I attempted to find a simple way to prevent the `enter` keypress event from propagating when an item in the dropdown is selected, but I wasn't able to find a solution without hacking into `ember-power-select`. But maybe I missed something.
- I wasn't able to actually write a test for pressing the enter key in a form. From what I can tell this isn't possible with jQuery. Instead, I tested that the `onSubmit` action is called when an input of type submit within the form is clicked. …

Makes paper-form an actual html form

---

CHANGELOG.md
addon/components/paper-form.js
addon/components/paper-input.js
addon/components/paper-radio-group.js
addon/templates/components/paper-form.hbs
addon/templates/components/paper-input.hbs
addon/templates/components/paper-radio-group.hbs
tests/integration/components/paper-form-test.js
tests/integration/components/paper-input-test.js
tests/integration/components/paper-radio-group-test.js

Hi and thanks again for this great addon! As recently discussed in slack I looked across existing components and added the ability to customize the sub-components that are yielded by parent-components. 
Autocomplete sub-components were already configurable. I left out the card-components because as far as I get it they are only provided because of styling concerns and extending them should be enough when you need to customize those.

Enhance customizability paper-{form, input, radio-group}

---

tests/dummy/app/styles/demo.scss
tests/dummy/app/templates/demo/input.hbs

Simply add some documentations for text-input.
Closes #668

text-input: add an exemple for helper text

---

addon/components/paper-input.js
addon/mixins/validation-mixin.js

because `computed.or` does not coalesce to bool, we otherwise end up with the number of errors instead of true in `isInvalid` and `isInvalidAndTouched`
Signed-off-by: Anthony Pessy <anthony.pessy@gmail.com>

use computed.bool instead of directly messages length

---

tests/dummy/app/templates/demo/input.hbs
tests/dummy/app/templates/demo/slider.hbs
tests/dummy/app/templates/index.hbs

The `flex` attribute was replaced in favor of `flex-X` classes.
Closes #673

replace flex attribute by flex class

---

package.json

`qunitjs` is a dependency of `ember-cli-qunit`. By not explicitly stating the version we want, we get the latest 2.x version. The problem is that anything after 2.2.1 breaks our tests at the moment.

Specifies exact version of qunitjs.

---

addon/components/paper-dialog-content.js

paper-dialog registered event handlers for each image in the dialog, because the size of the content can change when they load. It never cleaned up these handlers, which could cause tests to fail if the dialog in the test contained an image.

Clean up event handlers in paper dialog

---

app/styles/color-palette.scss
app/styles/default-theme.scss
lib/angular-scss-filter.js

For some reason the foreground colors are set during preprocessing to fixed values, making it impossible to alter them using SASS variables. This PR replaces the generated constants with SASS expressions, making it possible to override them, and strips dead code from `lib/angular-scss-filter.js`.

Consistent SASS theme colors

---

CHANGELOG.md
addon/components/paper-dialog.js
addon/templates/components/paper-dialog.hbs
tests/dummy/app/templates/demo/dialog.hbs
tests/integration/components/paper-dialog-test.js

Add a way to disable the opaqueness of the paper-dialog.
Combined with `origin` and little css on `md-dialog` you can do nice "popover panels" next to clicked buttons, etc.

can disable paper-dialog's backdrop opaqueness

---

index.js
package.json
yarn.lock

This change wraps the browser specific libraries with if (typeof FastBoot === 'undefined') {...} check so that they are eval'd and run in browser but only eval'd and skipped in Node.
This prepares the addon for the upcoming FastBoot 1.0. See ember-fastboot/ember-cli-fastboot#387
cc: @miguelcobain

Prepare for FastBoot 1.0

---

addon/components/paper-chips.js

Fixes #611 (paper-chips throws error on focus out on Firefox)

Chips: pass event into focusMovingTo

---

addon/components/paper-chips.js

Explicitly closing the autocomplete component on inputBlur broke the ability to add custom items to the chips element (assuming requireMatch is not true).  It doesn't appear to be necessary for any other purpose.

Chips: Don't explicitly close autocomplete on inputBlur - fixes #587

---

addon/components/paper-chips.js
addon/templates/components/paper-chips.hbs
addon/templates/components/paper-contact-chips.hbs

Add the ability to click anywhere in the chips element to give the input focus, plus the ability to click on a chip to focus it.  This makes the chips element behave more like its Angular Material counterpart, which supports these interactions.

Chips: Add missing mouse interactions

---

addon/templates/components/paper-chips.hbs
addon/templates/components/paper-contact-chips.hbs

This allows for customisable searching in Chips autocomplete (beyond just specifying the `searchField`).  I would have done this sooner, but I've only just hit the need for it and realised that these aren't already being passed through...

Chips: Pass search and matcher through to autocomplete

---

addon/components/paper-tab.js
addon/components/paper-tabs.js

It fixes the tab's dimensions when inside a scaled down parent using CSS transform (ex: dialog)
fix #771

paper-tabs: use offsetWidth instead of getBoundingClientRect

---

addon/templates/components/paper-menu.hbs

This can be very useful in more advanced scenarios. The yielded actions are practically useless without the dropdown's unique id.

Yield the dropdown public API from paper-menu

---

README.md
tests/dummy/app/templates/index.hbs

Version 0.2 documentation is being hosted by [Forge 512](https://forge512.com/) via github.io.  See [docs](https://forge512.github.io/ember-paper/).  This PR adds a link to the README and the index page of the dummy app.
A snapshot of the dummy app addition is below.  My thought was this leaves space to add links to other versions as needed.

add links to hosted v0.2 documentation

---

tests/dummy/app/templates/demo/speed-dial.hbs

Fix typo in speed-dial demo

---

addon/templates/components/paper-toast.hbs
addon/templates/components/paper-toaster.hbs
tests/dummy/app/controllers/demo/toast.js
tests/dummy/app/styles/demo.scss
tests/dummy/app/templates/demo/toast.hbs

Due to `paper-toast` being tagless and wormholing the `paper-toast-inner` component, the `class` attribute needs to be passed through in order to allow additional CSS classes to be specified on the `md-toast` element.  Additionally, the `paperToaster` service should support a `toastClass` option (see AM's [$mdToast.simple()](https://material.angularjs.org/1.1.5/api/service/$mdToast#mdtoast-simple) documentation) do that toasts opened using the service can each have their own additional classes.
I've updated the `paperToaster` demo in a separate commit, so that you can choose whether to demo it or not.

Add support for additional CSS class on paper-toast

---

tests/dummy/app/controllers/demo/tabs.js
tests/dummy/app/templates/demo/tabs.hbs

The example for routable tabs is not updating the `selected` property correctly. Steps to reproduce:
1) While on the tabs page, click `Nested Route`
2) Navigate away from the tabs page by clicking one of the other links in the sidebar
3) Navigate back to the tabs page by clicking the tabs link in the sidebar
4) `Nested Route` will still be highlighted even though you are on `demo.tabs.index`
This is happening because the `currentRouteName` on the controller is diverging from the routerService's `currentRouteName`. Making the `currentRouteName` property `readOnly` on the controller fixes the issue.

Fix routable tabs example

---

addon/templates/components/paper-autocomplete-trigger.hbs
addon/templates/components/paper-autocomplete.hbs

Pass isTouched from paper-autocomplete to paper-autocomplete-trigger
and its inner paper-input.
External errors are not otherwise rendered because isTouched is always false on the inner `paper-input` component.

Make externally provided errors work with paper-autocomplete

---

addon/components/paper-progress-circular.js

I recently upgraded ember paper for my project and found that acceptance tests were failing left and right. I finally isolated the issue to this component, and found that renderCircle was getting caught in a recursive loop once the component started being destroyed. The tests were waiting on this component to finish rendering, and they would wait until the tests timed out.
At first glance it looks like I'm doing a lot here, but I'm just wrapping the contents of `renderCircle` inside an `if` statement (in fact, the same check that's being performed inside the `renderFrame` function defined inside this function).

Fix paper-progress-circular infinite loop in acceptance tests

---

addon/components/paper-form.js
tests/integration/components/paper-form-test.js

Add `onInvalid` action, invoked when trying to submit an invalid form.

[FEATURE] Add onInvalid action to form.

---

addon/components/paper-toast.js
addon/templates/components/paper-toast.hbs

Having a function that is named after an event on a tagless component is an error in glimmer. The paper-toast component has a method named `swipe`. Normally this isn't a problem because `swipe` is an official event registered with the event dispatcher. But when using `ember-gestures` there is a `swipe` event, making it impossible to use `paper-toast`. However, here, the tagless component has a method `swipe` out of coincidence. By renaming this method we solve the problem. This fixes issue #853.

resolve swipe name conflict

---

addon/templates/components/paper-autocomplete-trigger.hbs

Add autofocus flag to passThru hash to enable autofocus of autocomplete-trigger input

Add "autofocus" to autocomplete-trigger input

---

addon/components/paper-radio-group.js
tests/integration/components/paper-radio-group-test.js

component:paper-radio-group select() should handle 0 properly

---

addon/components/paper-button.js

If using `{{#paper-button href="..." target="_blank"}}` we need to pass through `rel="noopener noreferrer"` too.
https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

Add rel to paper-button attribute bindings

---

tests/dummy/app/templates/demo/sidenav.hbs

The code snippets were overwriting each other because they were both named `sidenav`. I have added more descriptive names to avoid this.

Fix sidenav code snippet references

---

addon/components/paper-backdrop.js

The 0.1.11v of ember-css-transitions seems to have removed it dependency on jquery, which also means the code below isn't working anymore (due to `parent()` being a jquery API)
This PR should fix it.

Ember-css-transition upgrade broke sidenav

---

addon/mixins/validation-mixin.js

[This deprecation](https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-meta-descriptor-on-object) in the latest version of ember causes the `validationErrorMessages` computed property to never update after it's initialized. Using `defineProperty` fixes this issue.

fix implicit creation of `validationErrorMessages` computed property in `validation-mixin`

---

tests/dummy/app/templates/demo/menu.hbs

This PR simply add an exemple in the dummy app with the `dense:true` value.
Turned out I implemented a similar feature using custom css when option was there all along but undocumented.

add 'paper-menu-content' example for 'dense'

---

addon/components/paper-select-options.js
addon/templates/components/paper-select-menu-inner.hbs
tests/integration/components/paper-select-test.js

Not sure why it was done this way to begin with, but rendering `md-select-header` outside of `md-content` make it sticky to the top which is a huge usability improvement.
Closes #938

render md-select-header outside of md-content

---

addon/components/paper-virtual-repeat.js

Closes #926
The `defaultAttrs` was probably wrapped in a computed property because of the new "leaking object state" eslint error.
Since creating a computed property poses an issue here, let's simply setup it in `init()` lifecycle method.

Fix setup of defaultAttrs for paper-virtual-repeat

---

addon/components/paper-tooltip.js
addon/mixins/ripple-mixin.js
addon/utils/browser-features.js

Improves scrolling and fixes warnings

make ripple touch events passive

---

addon/components/paper-grid-list.js
addon/components/paper-grid-tile.js
tests/dummy/app/templates/demo/grid-list.hbs
tests/integration/components/paper-grid-list-test.js

Continued from #809
closes #769
Rebased and ready to merge @miguelcobain 
cc @woohoou

Grid list: Handle tile order and length changes

---

addon/components/paper-autocomplete.js
addon/components/paper-input.js
tests/integration/components/paper-form-test.js

1. For paper-input, validate only when its value changes. 
2. For paper-autocomplete, validate only when selection is changed.

fix(...) input validations

---

addon/components/paper-tab.js
tests/dummy/app/templates/demo/tabs.hbs
tests/integration/components/paper-tabs-test.js

Hi, I saw that this issue #791 hasn't been fixed yet. Here's a PR to fix it. I've added a test and an example of a disabled tab in the dummy app.

Fix paper tab disabled

---

addon/components/paper-tabs.js

Im getting this error
`Assertion Failed: You modified "canPageBack" twice in a single render`
in mobile chrome which prevents the smoothly transition to hidden tabs.
I tracked it down to `this.fixOffsetIfNeeded();` which is executed everytime the `_selectedTab` change which at least in my use case, it can be changed both programatically (i.e `selected=someProperty`) or by the end user when clicked on a tab or the next, previous arrows.

Paper-tabs Assertion Failed: You modified canPageBack twice in a single render

---

app/styles/default-theme.scss

Just a simple fix for the deprecated `contrastColor` function to correctly call the new `paper-contrast-color` function

Correctly call 'paper-contrast-color'

---

addon/templates/components/paper-toaster.hbs
tests/dummy/app/templates/demo/toast.hbs
tests/integration/components/paper-toaster-test.js

In the angular implementation, they allow you to customize the button by using a ["highlightClass"](https://github.com/angular/material/blob/v1.1.4/src/components/toast/toast.js#L174):
> If set, the given class will be applied to the highlighted action button.<br/>
> This allows you to specify the highlight color easily. Highlight classes are `md-primary`, `md-warn`  and `md-accent

forward primary/warn configuration to the toasts' paper-button

---

CHANGELOG.md
README.md
addon/components/paper-dialog-inner.js
addon/components/paper-dialog.js
addon/mixins/translate3d-mixin.js
tests/integration/components/paper-dialog-test.js

Hello, I refactored jquery from the component and from the component integration tests, it seems to be working ok. I have three tests failing though.
1. `test('should only prevent scrolling behind scoped modal')`
2. `test('pressing escape triggers close action`)` this was failing even without the refactor.
3. `test('opening gives focus')`

paper-dialog no jquery

---

tests/dummy/app/templates/typography.hbs

I assume the missing slashes in the closing tags were just an oversight and not intentional.

Added missing slashes in closing tags of typography demo template

---

addon/templates/components/paper-input.hbs
tests/integration/components/paper-input-test.js

Adding aria-describedby attribute to input fields with reference to occasionally appearing info text element below the related field causes screen readers to read out input fields together with corresponding info text (mainly error notification, e.g. failed validation). This change matches [1.3.1 Info and Relationships](https://www.w3.org/WAI/WCAG21/Understanding/info-and-relationships.html) success criterion of WCAG 2.
Without this connection the info underneath the input field is being read out separately and for screen reader users it may not be clear which input element this info belongs to.

Associate input field with corresponding info messages for better a11y

---

addon/components/paper-icon.js
tests/integration/components/paper-icon-test.js

Icon's and related text element's meaning usually overlap. Which is why reading out icons' label is often redundant. Developers should be able to prevent screen reader from reading out paper-icons using aria-hidden attribute which is set to false by default. This change aims [WCAG2 Success Criterion 1.1.1: Non-text Content](https://www.w3.org/WAI/WCAG21/Understanding/non-text-content.html)

Improve paper-icon a11y

---

addon/templates/components/paper-select.hbs
tests/integration/components/paper-select-test.js

#941 removed the wrapping `md-content` tag in `paper-select` with `searchEnabled=true` which causes problems (#1025) in the `calculatePosition` method of `paper-select-menu` when the `paper-select` is clicked without any `options` available. 
This PR adds a `md-content` wrapper around the `searchMessageComponent` in `paper-select`.

fix missing md-content when displaying searchMessage in paper-select

---

addon/templates/components/paper-input.hbs
tests/integration/components/paper-input-test.js

It allows us to add `title` attribute to the input field - improvement for screen readers.

Allow to add title attribute to paper-input

---

tests/dummy/app/templates/demo/select.hbs

previous implementation made it impossible to select an item from the list.

fix searchable paper-select in dummy app

---

addon/components/paper-checkbox.js
addon/templates/components/paper-checkbox.hbs
tests/integration/components/paper-checkbox-test.js

I've added support for
and the `role="checkbox"`
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/checkbox_role
@miguelcobain Should I also add `type="checkbox"`? I see that the angular's version has it but I am not sure.

Make checkbox accessible

---

addon/components/paper-radio-base.js
addon/components/paper-radio-group-label.js
addon/components/paper-radio-group.js
addon/templates/components/paper-radio-group-label.hbs
addon/templates/components/paper-radio-group.hbs
app/components/paper-radio-group-label.js
tests/integration/components/paper-radio-group-label-test.js
tests/integration/components/paper-radio-group-test.js
tests/integration/components/paper-radio-test.js

I've added
I don't like the solution with `aria-labelledby` inside the `paper-radio-group` I was thinking about creating the new component `paper-radio-group-label` which will be yielded like `labelId` and it would have passed action that will set the `aria-labelledby` on the parent radio group component. But I think that would be a bigger change from component API perspective - what do you think about that?

Make radio button accessible

---

addon/templates/components/paper-select-content.hbs

In a project where I'm using the latest beta of ember-paper, I noticed my paper selects were not closing when clicking outside the menu options area. Seems the paper-backdrop does not have the onClick value set. Making it call the dropdown.actions.close fixed the issue as per this PR.
Not 100% sure if I'm using the component somehow wrong as in the demo it seems to work. In any case, if this fix is relevant do merge this in - if not, ignore! Thanks for all the work on this. :)

Fix paper select click-catcher to call dropdown.actions.close on click

---

tests/dummy/app/styles/demo.scss
tests/dummy/app/templates/components/page-toolbar.hbs

The idea is to have a more visible link between the demo website and the github repository.

add little github icon in demo toolbar

---

addon/components/paper-tab.js
addon/components/paper-tabs.js
addon/templates/components/paper-tabs.hbs
tests/integration/components/paper-tabs-test.js

Hopefully:
- Superseed #982 
- Fixes #858
- Fixes #759 
- Fixes #893 
I'm trying to take a fresh start at paper tabs offsets handling as they are may issues at the moment.
If they are things that I'm missing feel free to tell me.
Amongs the hopefully fixed issues:
- infinite rendering
- movingRight that is not properly set
- currentOffset that may not be set
- inkBar that may be rendered without proper left/right offset
- lot's of (I think) unnecessary 'updateXXX' calls
Issues yet to be fixed:
- when you paginate, it triggers a re-render that eventually calls 'fixOffset' which 'cancel' the pagination because it caused the selected tab to be partially hidden :sob:
**edit**:
To correct this 'fixOffset' issue that breaks the pagination I now call it in only 2 cases:
- upon first render to …

Trying to address paper-tabs issues

---

addon/components/paper-reset-button.js
tests/integration/components/paper-autocomplete-test.js
tests/integration/components/paper-reset-button-test.js

Problem:
When using the paper-autocomplete inside of a form, its clear button is triggering the forms submit action.  This is called because the button defaults to type="submit" inside of a form.
Changes:
- update the paper-reset-button type to button to avoid the default of
type="submit" when inside a form
- add tests for paper-reset-button and paper-autocomplete components

Prevent submitting a form when clicking clear in paper-autocomplete

---

addon/components/paper-input.js

Fix paper-autocomplete value being overriden when changed

---

index.js

I noticed this dep was missing for paper-autocomplete... `paper-autocomplete-trigger-container`

Missing dependency for paper-autocomplete

---

addon/components/paper-backdrop.js

This is a naïve fix for a problem I was experiencing in tests after updating Ember Paper, you can see an example here:
https://travis-ci.org/backspace/prison-rideshare-ui/builds/530523899#L578
It seems somewhat akin to what’s discussed in #925, but I’m definitely at the limit of my understanding of what’s happening. I only encountered this problem in tests.
Let me know if I can provide any details from the application that might help solve this differently.

Add guard against missing original.parentNode

---

tests/integration/components/paper-input-test.js

This shows the bug being described in #1092. Reverting
#1076 does fix it, but then presumably #1043 would return 😞

Add test for clearing paper-input

---

package.json

ember-paper is causing deprecation warnings for computed property overrides. The issue is stemming from `ember-composability-tools` and is fixed in version of v0.0.12 of that package. The related issue is [here](https://github.com/miguelcobain/ember-composability-tools/issues/23).

bump ember-composability-tools to v0.0.12 to fix deprecation warnings

---

addon/components/paper-speed-dial-actions-action.js

Clean PR for #1072 credits to @woohoou
Speed dial has wrong calculation when animation is "Scale".
The calculation of the delay is negative and it prevents click actions because the close animation start and the negative delay buttons disappear immediately so the release button event/action never trigger.

[CLEAN] Fix delay in transition at scale speed dial

---

package.json

```
~ $ node -v
v12.8.0
```
```
~ $ npm test
> ember-paper@1.0.0-beta.26 test 
> ember test
Environment: test
cleaning up...
Built project successfully.
```

Add support of node 12.x

---

index.js

Adds support for blacklist/whitelist with pod components.
Use only whitelist or blacklist, NOT both.
As a reminder, whitelist is an array of components which will be included in the build, as well as all of their dependencies...
i.e
```ts
['ember-paper']: {
whitelist: ['paper-autcomplete']
}
``` 
Would only include into the build:
```ts
[
'paper-autocomplete',
'paper-autocomplete/ebd-trigger',
'paper-autocomplete/eps-trigger',
'paper-autocomplete/ebd-content',
'paper-autocomplete/options',
'paper-autocomplete/no-matches-message',
'paper-autocomplete/highlight'
]
```
If nested, the "path" must be specified 
```ts
['ember-paper']: { 
whitelist: [
'paper-autocomplete/ebd-trigger'
]
}
```
Blacklist is harder to get right, use with caution, as it would only exclude this particular component. …

update whitelist/blacklist to support pods

---

addon/components/paper-autocomplete/ebd-content/template.hbs
addon/components/paper-autocomplete/eps-trigger/template.hbs
addon/components/paper-autocomplete/template.hbs
addon/components/paper-chips/template.hbs
addon/components/paper-menu/item/template.hbs
addon/components/paper-menu/template.hbs
addon/components/paper-select/ebd-content/template.hbs
addon/components/paper-select/template.hbs

The new changes to `paper-menu` `paper-select` `paper-chips` and `paper-autocomplete` had unnecessary usage of `fn` helper, the recommended way in octane is just
```ts
import { action } from '@ember/object';
export default class SomeComponent extends Component {
@action
open() {
//do stuff that needs this component's context
this.set('isOpen', true);
}
calculatePosition(e) {
//this function doesn't need component's context
e.getBoundingClientRect(); 
}
@action
async close(opt) {
//This function needs component's context and receives an argument
if(opt.id === this.selectedOpt.id) { //whatever
return await this.onClose();
}
}
}
```
```hbs
<button {{on "click" this.open}}>Open Stuff </button>
{{#if this.isOpen}}
<div {{did-insert this.calculatePosition}} ...attributes>
<button {{on "click" …
```

remove unnecesary "fn" helper

---

addon/components/paper-menu/item/template.hbs

`paper-menu/item` wasn't forwarding `...attributes`
Fixes #1125

Use splattributes for paper-menu/item

---

addon/components/paper-input.js
addon/components/paper-speed-dial.js
addon/mixins/events-mixin.js
addon/mixins/focusable-mixin.js

Fix [1134](https://github.com/miguelcobain/ember-paper/issues/1134)

Fix[1134] mouseEnter/Leave/Move deprecations by adding event listeners

---

addon/components/paper-menu/component.js
addon/utils/menu-position-calculator.js

fix paper menu positioning

---

addon/components/paper-select/component.js

Noticed paper-select doesn't implement child mixin anymore, this is a regression.

[regression] added child-mixin

---

addon/components/paper-menu/content/component.js
tests/integration/components/paper-menu-test.js

Fixes #1128 
Check for existence of query selector before getting first child

[Fixes #1128] Protect against null querySelector in PaperMenu#focusItem

---

addon/components/paper-input.js

Chrome 83 has removed the clear button from date inputs, which means that there's now no way to clear a date field and have its validity state correctly updated.  Since the `oninput` event fired when the first date component is cleared provides an empty string as the new value, we can detect this and override `validity.badInput` to immediately update our validity state in order to avoid leaving the field permanently flagged as invalid.
Fixes #1153

Mark date inputs as valid when (partially) cleared

---

addon/components/paper-autocomplete/reset-button/component.js

Click works on both mobile and desktop.
Fixes #1138 & #882

Use click instead of mouseUp to clear autocomplete (allowClear=true)

---

.github/workflows/ci.yml
config/ember-try.js

Hey I just noticed that Ember 3.28 is showing up on the ember-try scenarios (but I didn't see a PR that added that 🤔)
Just a minor thing: we probably don't need that since the current version of Ember in the repo is 3.28 so the normal `Tests` will be using that version.
Happy to leave it there too but it's just a tiny bit of an efficiency to remove it 👍

remove Ember 3.28 from ember-try scenarios

---

.github/workflows/lint-to-the-future.yml

Hey folks 👋 now that we've started using lint-to-the-future from [#1212](https://github.com/miguelcobain/ember-paper/pull/1212) it's worth setting up the dashboard that comes with it.
I know @Subtletree mentioned opening a quest issue for Octane etc, but this dashboard is a bit of a simpler way of keeping track of lints that we want to fix 👍 If you want to see a demo of it you can look at https://mansona.github.io/ember-paper/lint-to-the-future/ which I just setup to make sure that it was working before creating this PR

Setting up the lint-to-the-future dashboard

---

addon/components/paper-tabs.js
addon/templates/components/paper-tabs.hbs

This is part of the same work that I'm doing in https://github.com/miguelcobain/ember-paper/pull/1220 
I am trying to update classes that use ParentMixin and Child Mixin to modern syntax so that I can update the `ember-composability-tools` addon and remove a bunch of deprecations. This is all to bring Ember 4.0 support 👍

update paper-tabs to class syntax

---

addon/components/paper-tab.js

This is part of the same work that I'm doing in https://github.com/miguelcobain/ember-paper/pull/1220 
I am trying to update classes that use ParentMixin and Child Mixin to modern syntax so that I can update the `ember-composability-tools` addon and remove a bunch of deprecations. This is all to bring Ember 4.0 support 👍

update paper-tab to use native class syntax

---

addon/components/paper-item.js

This is part of the same work that I'm doing in https://github.com/miguelcobain/ember-paper/pull/1220 
I am trying to update classes that use ParentMixin and Child Mixin to modern syntax so that I can update the `ember-composability-tools` addon and remove a bunch of deprecations. This is all to bring Ember 4.0 support 👍

update paper-item to use native class syntax

---

addon/components/paper-grid-list.js

Hey folks 👋  I'm still aiming to remove as many deprecations as I can, and my next target is to try to upgrade the `ember-composability-tools` dependency
But before I do that I need to convert each of the components that use it to glimmer components. I'm doing that step by step and trying to keep the change as small as possible. 
~~This PR introduces `ember-classic-decorator` to try to keep the PR diff as small as possible. This was recommended by the lining setup to prevent me from needing to convert all `this.get()` and `this.set()` calls in this PR (making it harder to follow)~~
I had originally used `ember-classic-decorator` since that's what the lint message suggested, but it seemed to break in earlier Ember versions so I just dropped it and ignored the lint error (temporarily) 👍 …

Convert PaperGridList to native class syntax

---

.github/workflows/ci.yml

This is adding https://github.com/mainmatter/continue-on-error-comment so we can get a green CI for things that we expect to pass 👍

add continue-on-error-comment

---

package-lock.json
package.json
tests/dummy/config/deprecation-workflow.js

This will allow us to start tackling a single deprecation at a time and not be totally blown away by warnings when running the test suite 🙈 
We can change each of the handlers to `throw` when we want to tackle one deprecation at a time 👍 https://github.com/mixonic/ember-cli-deprecation-workflow#handlers

add ember-cli-deprecation-workflow

---

index.js
package-lock.json
package.json

fix: Ember is not defined error

---

.github/workflows/ci.yml

I discovered why continue-on-error-comment wasn't working for people creating PRs from forks. You can read more here: https://github.com/mainmatter/continue-on-error-comment#permissions

apply fix to allow continue-on-error-comment to work

---

package-lock.json
package.json

Now that fixes have been released via https://github.com/miguelcobain/ember-css-transitions/issues/120#issuecomment-2408339530 we can upgrade!

build(deps): upgrades to `ember-css-transitions@^4.4.1`.

---

addon/components/paper-icon.js
addon/components/paper-ink-bar.js
addon/components/paper-progress-circular.js
addon/components/paper-progress-linear.js
addon/components/paper-sidenav-container.js
addon/components/paper-slider/component.js
addon/components/paper-speed-dial-actions-action.js
addon/components/paper-switch.js
addon/components/paper-tab.js
addon/components/paper-tabs.js
addon/components/paper-tooltip.js
addon/mixins/translate3d-mixin.js
tests/dummy/app/components/paper-api.js
tests/dummy/app/controllers/demo/slider.js

`htmlSafe` was removed in ember@3 from `@ember/string`
These use 'stacked PRs', for better clarity see PR dependency tree from graphite here: https://github.com/linc-technologies/ember-paper/pull/14#issuecomment-2418196586

refactor: migrates to `htmlSafe` from `@ember/template`.

---

addon/components/paper-backdrop.hbs
addon/components/paper-sidenav-container.js
addon/modifiers/lock-body.js
app/modifiers/lock-body.js
tests/dummy/app/styles/app.scss

The original reason for this change is because I wanted to add percy in #1296 but this is also required if you want the chrome "full screenshot" functionality to work. You can compare the preview build of this PR with the main demo app by doing the following
- open the preview app in chrome
- open dev tools
- run cmd-shift-p to open the command pallet
- type "screenshot" and select "Capture full size screenshot"
On main you'll see that scroll will be cut off and you can never get a full screenshot. This PR fixes that but needs to add some hacks to make the dialog inert. Personally I think it's a good tradeoff 👍

allow full-screen snapshots

---

.github/workflows/ci.yml
config/ember-try.js
tests/dummy/app/controllers/application.js
tests/dummy/app/templates/application.hbs
tests/dummy/app/templates/demo/tabs.hbs

TSIA!
Removes deprecations from the dummy app where it was directly accessing the application controller router:
- https://deprecations.emberjs.com/id/application-controller-router-properties

ci: adds no deprecations workflow
