.jshintrc, addon/components/paper-switch.js
Here's what I'm doing to try to get switch dragging working.  At the moment, the following works:
- Click anywhere on the switch to toggle the value (matches Material Angular behavior)
- Drag the switch more than halfway from one side to the other to toggle it.  From what I can tell, the Angular implementation doesn't quite do this right.
***
Closes #29
=> Implement switch dragging

README.md
Adds note to the `README` about Google Fonts and the Content Security Policy.
Closes #61
=> Add note about Google Fonts and CSP

addon/components/paper-radio.js, tests/unit/components/paper-radio-test.js
Radio buttons should not be able to be checked while disabled.
=> Fix checking a disabled radio-button

app/styles/paper-text.scss
=> Fix input radius on iOS

package.json
I changed the content policy in the Read me to be protocol independent. Also updated to the newest version of Ember CLI
=> Changed the content policy + Ember CLI update

addon/components/paper-slider.js
=> Added bounds and type validation to keyboard input handler

addon/components/paper-card-footer.js, app/components/paper-card-footer.js, app/styles/paper-card.scss, tests/dummy/app/templates/card.hbs
This adds support for adding a .md-actions div as in the angular material project.
=> Add support for .md-actions to {{paper-card}}

addon/components/paper-input.js
Demo: http://chrisitananese.github.io/ember-paper/#/input
The biography-textareas height now grows dynamically as shown on https://material.angularjs.org/latest/#/demo/material.components.input.
=> Added dynamic height to textarea

addon/components/paper-grid-list.js
fixes #196 
Fix assertion thrown when invalidating destroyed `paper-grid-list` component.
=> fixes #196

.npmignore, .watchmanconfig, bower.json, config/ember-try.js, config/environment.js, package.json, tests/dummy/app/app.js, tests/helpers/destroy-app.js, tests/helpers/module-for-acceptance.js, tests/helpers/resolver.js, tests/helpers/start-app.js, tests/index.html
Upgrade the Ember CLI to `v1.13.12`.
Closes #218
=> Update Ember CLI version

CHANGELOG.md, addon/components/paper-autocomplete.js
When changing model, change searchText
=> Listen for model changes

app/templates/components/paper-menu-container.hbs, app/templates/components/paper-menu-content.hbs, app/templates/components/paper-select-container.hbs
Fixes #254
This allows targeting this backdrop for z-index, so that clicks work properly.
While I'm here, I added classes to the rest of the backdrops.
=> Add class to backdrops

CHANGELOG.md, addon/mixins/proxiable-mixin.js
Fixing didInsertElement deprecation on proxiable-mixin #237
=> Fix for #237

CHANGELOG.md, addon/components/paper-icon.js, app/templates/components/paper-autocomplete.hbs, app/templates/components/paper-input.hbs, app/templates/components/paper-select.hbs, tests/dummy/app/templates/autocomplete.hbs, tests/dummy/app/templates/button.hbs, tests/dummy/app/templates/card.hbs, tests/dummy/app/templates/checkbox.hbs, tests/dummy/app/templates/components/example-item.hbs, tests/dummy/app/templates/divider.hbs, tests/dummy/app/templates/grid-list.hbs, tests/dummy/app/templates/icons.hbs, tests/dummy/app/templates/index.hbs, tests/dummy/app/templates/input.hbs, tests/dummy/app/templates/list-controls.hbs, tests/dummy/app/templates/list.hbs, tests/dummy/app/templates/menu.hbs, tests/dummy/app/templates/paper-select.hbs, tests/dummy/app/templates/progress-circular.hbs, tests/dummy/app/templates/progress-linear.hbs, tests/dummy/app/templates/radio.hbs, tests/dummy/app/templates/sidenav.hbs, tests/dummy/app/templates/slider.hbs, tests/dummy/app/templates/switch.hbs, tests/dummy/app/templates/toolbar.hbs, tests/dummy/app/templates/typography.hbs, tests/integration/components/paper-icon-test.js
See individual commits for details.
=> Improve `paper-icon`: docs update w/ positional params, iconClass binding fix

addon/components/paper-progress-linear.js, app/templates/components/paper-progress-circular.hbs, app/templates/components/paper-progress-linear.hbs
Migrate `{{paper-progress-circular}}` to 1.0.0 styles and template changes.
=> Fix template issues with paper-progress-circular

README.md
For easier access while reading the install instructions.
=> Add docs link inside the docs

tests/dummy/app/templates/autocomplete.hbs, tests/dummy/app/templates/list-controls.hbs, tests/dummy/app/templates/paper-select.hbs
Added `onchange` functions to the demo app per component requirements.
=> Updated onchange functions in the demo app

CONTRIBUTING.md, README.md
Here's something to start off the contributing guide. As we discuss questions, this would be a good place to document decisions and established standards and procedures.
=> CONTRIBUTING.md, initial commit, WIP.

CONTRIBUTING.md
Capitalization rules, as discussed on slack #ember-paper.
=> Updated capitalization rules camelCase

package.json, tests/dummy/app/router.js, tests/dummy/app/templates/application.hbs, tests/dummy/config/environment.js
=> Dummy app buffup

addon/components/paper-input.js
onInvalid was firing way more than it should have been.
=> Fixed lastIsInvalid -- now being set properly

tests/dummy/app/components/paper-api.js, tests/dummy/app/controllers/application.js, tests/dummy/app/controllers/layout/child-alignment.js, tests/dummy/app/controllers/layout/introduction.js, tests/dummy/app/helpers/array.js, tests/dummy/app/router.js, tests/dummy/app/styles/demo.scss, tests/dummy/app/styles/layout-demo.scss, tests/dummy/app/templates/application.hbs, tests/dummy/app/templates/components/page-toolbar.hbs, tests/dummy/app/templates/layout/child-alignment.hbs, tests/dummy/app/templates/layout/introduction.hbs, tests/dummy/app/templates/layout/layout-children.hbs, tests/dummy/app/templates/layout/layout-containers.hbs
Preview: http://awesan.com/ember-paper/#/layout/introduction
=> Layout documentation

addon/components/paper-input.js, app/templates/components/paper-input.hbs, tests/integration/components/paper-input-test.js
=> Prevent redundant on invalid (BUG FIX)

tests/dummy/app/templates/demo/radio.hbs
Additional documentation for radio buttons usage with images.
=> Added radio images to docs

tests/integration/components/paper-input-test.js
=> Tests for paper-input hasValue property

tests/dummy/app/templates/layout/child-alignment.hbs, tests/dummy/app/templates/layout/introduction.hbs
=> Fix layout docs

vendor/propagating.js
Includes bugfix for:
https://github.com/josdejong/propagating-hammerjs/issues/6
Refactor for hammer.js ^2.0.6:
https://github.com/josdejong/propagating-hammerjs/commit/57bcae9a015c95c41d31c46eae8f9eabdb9a800e
=> Update vendor/propagating.js to 1.4.6

tests/dummy/app/templates/layout/layout-containers.hbs
=> wrong code for shown snippet

package.json
The new version has the `async` fix for acceptance testing done in this PR
https://github.com/peec/ember-css-transitions/pull/14
=> Update ember-css-transitions to latest version.

addon/components/paper-select-menu-trigger.js, addon/components/paper-select-menu.js, app/components/paper-select-menu-trigger.js, app/templates/components/paper-select-menu.hbs, tests/dummy/app/controllers/demo/select.js
Had to extend basic-dropdowns trigger in order to add the attributeBinding for disabled to get the styling of disabled selects correct.
=> Select disabled styling

addon/components/paper-autocomplete-trigger.js, addon/components/paper-autocomplete.js, tests/dummy/app/controllers/demo/autocomplete.js, tests/dummy/app/templates/demo/autocomplete.hbs, tests/integration/components/paper-autocomplete-test.js
=> Don't show dropdown if paper-autocomplete has a selected value and

app/templates/components/paper-form.hbs, tests/integration/components/paper-form-test.js
=> Added ability to use submit button built into the form

README.md
=> README update - 1.0 reliance on Ember 2.3.x and higher

tests/dummy/app/templates/application.hbs
there is no form route so I removed it
=> [DEMO]: remove form from components

app/templates/components/paper-sidenav.hbs
Not really sure, but this looks right.
=> Fix old/missing sidenav attributes

addon/components/paper-slider.js
Fixes the possibility to change the slider through clicking while it's disabled.
=> Fixes bug in disabled slider

.travis.yml
Should build faster and is the LTS anyway.
=> Use Node 6 at Travis

addon/components/paper-button.js
This especially works well with data URIs
=> Allows you to use the html5 download attribute

addon/components/paper-autocomplete.js, addon/templates/components/paper-autocomplete-content.hbs, testem.js, tests/integration/components/paper-autocomplete-test.js
Autocomplete should support dropdownClass attribute similar to e-p-s
=> feat(ac): respect dropdownClass just like e-p-s

package.json, yarn.lock
=> Upgrade ember-composability-tools to v0.0.9

tests/dummy/app/templates/addons.hbs
This is a component I've been using lately in some corber projects, it has work to do, but, I think people can benefit from what it is at this point.
=> Add new addon by betocantu93

app/styles/ember-paper.scss, app/styles/overrides/paper-menu.scss
=> fix css issue when dense=true and content is scrollable

tests/dummy/app/templates/addons.hbs
Hi, @miguelcobain. Thanks for your work on `ember-paper`! 
I've created an addon for modals https://github.com/onechiporenko/ember-paper-modals-manager. I hope it will be useful for others.
=> Add `ember-paper-modals-manager` description to `addon`-page

addon/components/paper-autocomplete-trigger.js
As long as I can see this is working, and there is no tests for this using jquery
=> paper-autocomplete no jquery

tests/integration/components/paper-progress-linear-test.js
=> paper-progress-linear no jquery

tests/integration/components/paper-icon-test.js
=> paper-icon no jquery

tests/integration/components/paper-divider-test.js
Refactor jquery from paper-divider test
=> paper-divider no jquery

tests/integration/components/paper-card-test.js
Refactor jquery paper-card from test
=> paper-card no jquery

tests/integration/components/paper-button-test.js
=> paper-button no jquery

addon/components/paper-switch.js
Refactor jquery from paper-switch
=> paper-switch no jquery

addon/mixins/ripple-mixin.js
Refactor jquery from ripple-mixin
=> ripple-mixin no jquery

addon/components/paper-input.js, tests/integration/components/paper-input-test.js
I'm not quite sure about the setValue, if I didn't validated the value, it placed undefined in the inputs...
```javascript
setValue(value) {
if (this.element.querySelector('input, textarea').value !== value && value) {
this.element.querySelector('input, textarea').value = value;
}
},
```
=> paper-input no jquery

addon/components/paper-tooltip.js, tests/dummy/app/templates/demo/tooltip.hbs, tests/integration/components/paper-tooltip-test.js
Docs, tests and component jquery refactor
=> paper-tooltip no jquery

addon/components/paper-toast.js, tests/dummy/app/templates/demo/toast.hbs, tests/integration/components/paper-toast-test.js, tests/integration/components/paper-toaster-test.js
Refactor jquery from paper-toast
=> paper-toast no jquery

tests/integration/components/paper-checkbox-test.js
=> paper-checkbox no jquery

tests/integration/components/paper-radio-group-test.js
=> paper-radio-group no jquery

addon/components/paper-chips.js
Refactor jquery from paper-chips.js
=> paper-chips no jquery

addon/components/paper-progress-circular.js, tests/integration/components/paper-progress-circular-test.js
Refactor jQuery from paper-progress-circular from tests and component
=> paper-progress-circular no jquery

addon/components/paper-grid-list.js, addon/components/paper-grid-tile.js, tests/integration/components/paper-grid-list-test.js
Refactor jquery from component and tests
=> paper-grid no jquery

addon/components/paper-select-content.js, addon/components/paper-select-menu-inner.js, addon/components/paper-select-menu.js, addon/components/paper-select-options.js, package-lock.json
Refactor jquery from paper-select
=> paper-select no jquery

addon/components/paper-virtual-repeat-scroller.js, addon/components/paper-virtual-repeat.js, tests/integration/components/paper-virtual-repeat-test.js
Refactor jquery from paper-virtual-repeat-scroller.js, paper-virtual-repeat.js and tests.
=> paper-virtual-repeat no jquery

index.js
This is a follow up of the #1021 PR, this will only import the css of the whitelist-blacklist, as a reminder, you can only use one at the same time
=> blacklist-whitelist-styles

addon/components/paper-tabs.js
=> Fix infinite rendering issue with paper-tabs

tests/dummy/app/templates/addons.hbs
New addon I was using as in-repo-addon and I was able to abstract it for other projects
[ember-paper-flatpickr](https://github.com/betocantu93/ember-paper-flatpickr)
=> add ember-paper-flatpickr

tests/integration/components/paper-progress-circular-test.js, tests/integration/components/paper-virtual-repeat-test.js
Add waitUntil before trying to get the selector _transform_ for some reasons, the transform is updated after.
=> Trying to fix the travis build

addon/components/paper-autocomplete/ebd-content/template.hbs, addon/components/paper-menu/trigger/template.hbs, app/components/paper-snackbar-text.js
Hi!
As I was setting up a new app using ember-paper and embroider but i got several error at build time.
This was the necessary fix to make i work.
The 2 changes on comments position were necessary to fix this syntax error: 
https://github.com/glimmerjs/glimmer-vm/blob/6a4c85370d24640f31812036f5e75f8ffff06df7/packages/@glimmer/syntax/lib/parser/handlebars-node-visitors.ts#L216
The deleted file seem to be a forgotten file from a component renaming.
=> Embroider compatibility

app/styles/default-theme.scss
One of the apps I work with use heavily a fourth palette... so this enables the reuse of the mixin with ease
=> expose theme-variables mixin

package-lock.json, package.json
=> build(deps): updates to `ember-css-transitions@^3.1.0`.

package.json, pnpm-lock.yaml, tests/dummy/config/deprecation-workflow.js
Fixes https://github.com/adopted-ember-addons/ember-paper/issues/1283
=> make sure ember-cli-deprecation-workflow config is up to date

tests/dummy/app/controllers/catalog.js
eases snapshot difference detection.
=> chore(tests/dummy/app/controllers/catalog): stabilises catalog contacts.

package.json, pnpm-lock.yaml
current target branch has been merged upstream.
=> chore(deps): updates to `release-plan@^0.11.0`.
